In [1]:
import numpy as np

In [2]:
train = np.load('../train/train_set.npz')
train_unique, train_counts = np.unique(train['y_tra'], return_counts=True)
dict(zip(train_unique, train_unique))

{0: 0, 1: 1}

In [3]:
print(train['X_tra'])

[[1 3 1 ... 1 1 2]
 [4 3 3 ... 2 4 2]
 [1 2 1 ... 2 2 4]
 ...
 [4 1 3 ... 4 3 3]
 [1 1 4 ... 4 2 4]
 [2 2 2 ... 2 4 3]]


In [19]:
test_balance = np.load('../test/balanced_test_set.npz')
balance_unique, balance_counts = np.unique(test_balance['y_tes'], return_counts=True)
dict(zip(balance_unique, balance_counts))

{0: 189, 1: 189}

In [31]:
print(test_balance['y_tes'])

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [24]:
print(test_balance['y_tes'])

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [20]:
test_balance = np.load('../test/imbalanced_test_set.npz')
imbalance_unique, imbalance_counts = np.unique(test_balance['y_tes'], return_counts=True)
dict(zip(imbalance_unique, imbalance_counts))

{0: 1664, 1: 189}

In [3]:
import numpy as np

# 查看数组的维度和形状
print("数组形状:", train['y_tra'].shape)
print("数组维度:", train['y_tra'].ndim)

# 查看数据类型
print("数据类型:", train['y_tra'].dtype)

# 查看唯一值和数量统计
unique_values, counts = np.unique(train['y_tra'], return_counts=True)
print("唯一值:", unique_values)
print("数量统计:", counts)

数组形状: (16674, 1)
数组维度: 2
数据类型: int64
唯一值: [0 1]
数量统计: [14946  1728]


In [1]:
import pandas as pd
data = pd.read_csv('train_set.csv')
# 导出为FASTA格式
with open('output.fasta', 'w') as f:
    for idx, row in data.iterrows():
        f.write(f'>{row["label"]}\n{row["seq"]}\n')